## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

dist: xenial

os:
  - linux
  #- osx
  
env:
  - JULIA_CMDSTAN_HOME="$HOME/cmdstan-2.22.1/"
  
before_install:
  - OLDWD=`pwd`
  - cd ~
  - wget https://github.com/stan-dev/cmdstan/releases/download/v2.22.1/cmdstan-2.22.1.tar.gz
  - tar -xzpf cmdstan-2.22.1.tar.gz
  - make -C $JULIA_CMDSTAN_HOME build
  - cd $OLDWD
  
julia:
  - 1.4
  - nightly
  
notifications:
  email: false
  
git:
  depth: 99999999

matrix:
  allow_failures:
  - julia: nightly
  - os: osx

after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl
